name: Zip and Push
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: src
          recursive: true
          dest: extension.zip
      # debug
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/extension.zip
  # You may pin to the exact commit or the version.
  # uses: mnao305/chrome-extension-upload@eb962593ec36f9e70426b6ed9b33f40ae270d523

      - uses: mnao305/chrome-extension-upload@3.0.0
        with:
          # path & filename to a zip file
          file-path: extension.zip
          # extension id
          extension-id: iehcfhcebligckfppbapaicknhhpndji
          # client id
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          # client secret
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          # refresh token
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
