name: Zip and Push
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: src
          recursive: true
          dest: extension.zip
        
          
